spring:
  application:
    name: store_service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 587
    username: 121632940@qq.com
    password: 腾讯校验码
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/

server:
  port: 8082

## mybatis   mybatis-plus: 映射关系选要确定
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml